/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.99.0
  Forc version: 0.66.6
  Fuel-Core version: 0.40.0
*/

import { ContractFactory as __ContractFactory, decompressBytecode } from "fuels";
import type { Provider, Account, DeployContractOptions } from "fuels";

import { ContractExample } from "./ContractExample";

const bytecode = decompressBytecode("H4sIAAAAAAAAA6VUz08TQRR+LRX3YjIR1LoEGZNC8KJrNKbH3bSb7VKabvTCwaWbGBtMoJRSGhIvPXoUEpUjf4GZthe8NZ565OjNHiWhSQ+aYDjgN7tDRAQvNmlm5v34vrffezP60KA6UYLC3xWh1p5/0o2xkxPpI/3Qoy0a6dVMmisNKKabAWFd9R2x6mdErJYjbcJKEbPGpX0NtjX9gIgfPaKF437cO+4ngHOkZ/alfx3+dc8RXeyTXqYdBBbTPKdDgU0aOFzYSXFUEVsFD4UcdspkVsKEvQZ77QKOr4qjDn/dc1pyz8GxpDgMyeFlOgYwy77N4Gebch/i58abzB5vwlaGbRPrCnKW/LxY8YriS1BArmVoIVZGsMAyGPwCmAx85Yks8qP6yuAQntOuSh/2HnLCFTUNpU0/YOdr/yxrl3xeXvSAcduz+CkXDywOrnYzwmu/lXi+M4wzm3W9fEcLXNixIlag7pu1LF3Degt8OZWDejl4/9JsL+QttnlQYPAb5/1CL+7TmJXojhVkX4ga8zQFPPMSvE+qBxuICb/7ghihYiqIMS7B2VYxy9B2A/2ooA/L96zE04ZJcczJ6yeo5VzOR6VhctEmgt7J5xZRLZugmSxqz1bJy7c4dElJG9bp0iHNYBYxFzwJ30LgsiR03lVnEZ0FNJRn8U2e/Wdi0i+KO6hpirnMvOGmuo0cxcA/ijmKT7iPm6zAzZl5otnJrKl7VWJu1lx0CXeEmehJtTQw75cGxgN8n4GeyTsAntYOeiXvxF507qSjcycNXy/ai00Vq8kztLnr2ZitfOsNsB6emRnMSDgz+6r//XAGnQ5XM8nhk3fuolmcUjpy4PbxzcgTUhPwtIfRuYXaOGZQzF63mTltMXpHdPW9Fr0XemaXdKdPDdjk3RpzuQmN4j76AfyY7Ev4tvzA/yejHeR9QOzcEf2Bs0VknmJBfy7nPBigjgx6hjsIG5M26DAqsbZl/L/x0mfwwlyFx0M84MIODbkm3zaFmf5fTKwSL/zeS/Biv7Xrk/6dQRc6jYnJGAd61V+u10vljcqL+qvVSvRY4zcy/AVmlJuIyAUAAA==");

export class ContractExampleFactory extends __ContractFactory<ContractExample> {

  static readonly bytecode = bytecode;

  constructor(accountOrProvider: Account | Provider) {
    super(
      bytecode,
      ContractExample.abi,
      accountOrProvider,
      ContractExample.storageSlots
    );
  }

  static deploy (
    wallet: Account,
    options: DeployContractOptions = {}
  ) {
    const factory = new ContractExampleFactory(wallet);
    return factory.deploy(options);
  }
}
