/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.92.1
  Forc version: 0.61.2
  Fuel-Core version: 0.31.0
*/

import type {
  BN,
  BigNumberish,
  BytesLike,
  Contract,
  DecodedValue,
  FunctionFragment,
  Interface,
  InvokeFunction,
} from 'fuels';

interface ContractAbiInterface extends Interface {
  functions: {
    seven: FunctionFragment;
    zero: FunctionFragment;
  };
}

export class ContractAbi extends Contract {
  interface: ContractAbiInterface;
  functions: {
    seven: InvokeFunction<[], BN>;
    zero: InvokeFunction<[], BN>;
  };
}
