/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.99.0
  Forc version: 0.66.6
  Fuel-Core version: 0.40.0
*/

export { ScriptExample } from './ScriptExample';
export { ScriptExampleLoader } from './ScriptExampleLoader';
