/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.99.0
  Forc version: 0.66.6
  Fuel-Core version: 0.40.0
*/

import {
  Account,
  BigNumberish,
  BN,
  decompressBytecode,
  Script as __Script,
} from 'fuels';

export type ScriptExampleInputs = [];
export type ScriptExampleOutput = BN;

export type ScriptExampleConfigurables = Partial<{
  SECRET_NUMBER: BigNumberish;
}>;

const abi = {
  "programType": "script",
  "specVersion": "1",
  "encodingVersion": "1",
  "concreteTypes": [
    {
      "type": "u64",
      "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
    }
  ],
  "metadataTypes": [],
  "functions": [
    {
      "inputs": [],
      "name": "main",
      "output": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
      "attributes": null
    }
  ],
  "loggedTypes": [
    {
      "logId": "1515152261580153489",
      "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
    }
  ],
  "messagesTypes": [],
  "configurables": [
    {
      "name": "SECRET_NUMBER",
      "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
      "offset": 728
    }
  ]
};

const bytecode = decompressBytecode('H4sIAAAAAAAAA3VSPWvbUBQ9doSrqX5tHWqea9CQBm8VNENHCcnYqlzyoENTirDoLzCmdI3Gjv2gbcb8hKeto3+Cx44a2tLSCDwkYJPBOc92CBjyQNx377n3nnfPlZy5eAdYWJ3qdGN/JstJRSyX+ATY6v/MVr9oCw/O/CmOLouquiws1j2UZ8rkPFOBdrawJ7I3xbAUtaSnayrWQv4TkL+d7R6+yUtLIdJAi6SLSuIDj32Br0D9mw1sODoyOIWMM8jDgn0BctqssVVPi7QLOwl01dQSs8x9HMJuhQ1P+JbHWJUxi3aHdU2DdSLLk+fAZ9N74eKEXN/J+XyObW5XBgWS0APncG6Zo349x+o9/JLeDEnMNx3qnYNK44uplxfC8LlygW2+4xu+yslq1jcfIV8VGIcW9kNi4cjwj6jpXROjrQ/PINLSaZLzBzmbKs69NBL0c2rCeKyba19/MH7yUt/je+5zJw/GfdgiamS70d7kfR8VznCHsWorOsjGA2Iv9ib7A4rTDj2pRhBR6A0jYOwR8xtgz+mw9OSwdFvU9RF1dVN/xTXnPpoqyI/Wfp5t/Iz3zvqu+5vcU+NzNw3VpXax/stebeU7NnGbeWnqO9Q0HzFPpK+FkBcpNaRGC3Wt4bHRsMc/d7f253zQfsuVrc8VOSLWluACAAA=');

export class ScriptExample extends __Script<ScriptExampleInputs, ScriptExampleOutput> {

  static readonly abi = abi;
  static readonly bytecode = bytecode;

  constructor(wallet: Account) {
    super(bytecode, abi, wallet);
  }
}
