name: Deploy to NPM

on:
    push:
        branches: [master]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 16.19.0

            - name: Install yarn globally
              run: npm install -g yarn

            - name: Install dependencies
              run: yarn install

            - name: Run yarn build
              run: yarn build
              working-directory: ${{ github.workspace }}

            - name: Publish package
              run: yarn publish --access public --token ${{ secrets.ACCESS_NPM_TOKEN }}
